{{- if and .Values.supabase.enabled .Values.supabase.rest.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kurrier.fullname" . }}-rest
  labels:
    {{- include "kurrier.rest.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.supabase.rest.replicaCount }}
  selector:
    matchLabels:
      {{- include "kurrier.rest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.supabase.rest.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "kurrier.rest.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "kurrier.imagePullSecrets" (dict "Values" .Values "componentPullSecrets" nil) | nindent 6 }}
      serviceAccountName: {{ include "kurrier.serviceAccountName" . }}
      containers:
        - name: rest
          image: "{{ .Values.supabase.rest.image.repository }}:{{ .Values.supabase.rest.image.tag }}"
          imagePullPolicy: {{ .Values.supabase.rest.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: PGRST_DB_SCHEMAS
              value: {{ .Values.supabase.rest.dbSchema | quote }}
            - name: PGRST_DB_ANON_ROLE
              value: {{ .Values.supabase.rest.dbAnonRole | quote }}
            - name: PGRST_DB_USE_LEGACY_GUCS
              value: {{ .Values.supabase.rest.dbUseLegacyGucs | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kurrier.postgresql.secretName" . }}
                  key: {{ include "kurrier.postgresql.secretKey" . }}
            - name: PGRST_DB_URI
              value: "postgres://authenticator:$(POSTGRES_PASSWORD)@{{ include "kurrier.postgresql.host" . }}:{{ include "kurrier.postgresql.port" . }}/{{ include "kurrier.postgresql.database" . }}"
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "kurrier.jwt.secretName" . }}
                  key: {{ .Values.kurrier.jwt.secretKeys.jwtSecret }}
            - name: PGRST_APP_SETTINGS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "kurrier.jwt.secretName" . }}
                  key: {{ .Values.kurrier.jwt.secretKeys.jwtSecret }}
            - name: PGRST_APP_SETTINGS_JWT_EXP
              value: "3600"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.supabase.rest.resources | nindent 12 }}
      {{- with .Values.supabase.rest.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.supabase.rest.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.supabase.rest.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kurrier.rest.serviceName" . }}
  labels:
    {{- include "kurrier.rest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.supabase.rest.service.type }}
  ports:
    - port: {{ .Values.supabase.rest.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kurrier.rest.selectorLabels" . | nindent 4 }}
{{- end }}
