{{- if and .Values.supabase.enabled .Values.supabase.studio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kurrier.fullname" . }}-studio
  labels:
    {{- include "kurrier.studio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.supabase.studio.replicaCount }}
  selector:
    matchLabels:
      {{- include "kurrier.studio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.supabase.studio.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "kurrier.studio.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "kurrier.imagePullSecrets" (dict "Values" .Values "componentPullSecrets" nil) | nindent 6 }}
      serviceAccountName: {{ include "kurrier.serviceAccountName" . }}
      containers:
        - name: studio
          image: "{{ .Values.supabase.studio.image.repository }}:{{ .Values.supabase.studio.image.tag }}"
          imagePullPolicy: {{ .Values.supabase.studio.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: STUDIO_PG_META_URL
              value: "http://{{ include "kurrier.meta.serviceName" . }}:{{ .Values.supabase.meta.service.port }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kurrier.postgresql.secretName" . }}
                  key: {{ include "kurrier.postgresql.secretKey" . }}
            - name: DEFAULT_ORGANIZATION_NAME
              value: "Kurrier"
            - name: DEFAULT_PROJECT_NAME
              value: "Kurrier"
            - name: SUPABASE_URL
              value: "http://{{ include "kurrier.kong.serviceName" . }}:{{ .Values.supabase.kong.service.httpPort }}"
            - name: SUPABASE_PUBLIC_URL
              value: {{ .Values.kurrier.webUrl | quote }}
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "kurrier.jwt.secretName" . }}
                  key: {{ .Values.kurrier.jwt.secretKeys.anonKey }}
            - name: SUPABASE_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "kurrier.jwt.secretName" . }}
                  key: {{ .Values.kurrier.jwt.secretKeys.serviceRoleKey }}
            - name: AUTH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "kurrier.jwt.secretName" . }}
                  key: {{ .Values.kurrier.jwt.secretKeys.jwtSecret }}
            - name: LOGFLARE_API_KEY
              value: ""
            - name: LOGFLARE_URL
              value: ""
            - name: NEXT_PUBLIC_ENABLE_LOGS
              value: "false"
            - name: NEXT_ANALYTICS_BACKEND_PROVIDER
              value: "postgres"
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.supabase.studio.resources | nindent 12 }}
      {{- with .Values.supabase.studio.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.supabase.studio.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.supabase.studio.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kurrier.studio.serviceName" . }}
  labels:
    {{- include "kurrier.studio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.supabase.studio.service.type }}
  ports:
    - port: {{ .Values.supabase.studio.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kurrier.studio.selectorLabels" . | nindent 4 }}
{{- end }}
