global:
  storageClass: iscsi

config:
  webUrl: https://kurrier.vanclanjr.io
  davUrl: https://kurrier-dav.vanclanjr.io
  disableDrive: false
  disableLocalLogin: false

secrets:
  existingSecret: kurrier-secrets

dav:
  config:
    timezone: America/New_York
    inviteFrom: noreply@vanclanjr.io

ingress:
  enabled: true
  className: pomerium
  annotations:
    cert-manager.io/cluster-issuer: step-ca-issuer
    ingress.pomerium.io/preserve_host_header: "true"
  hosts:
    - host: kurrier.vanclanjr.io
      paths:
        - path: /
          pathType: Prefix
          service: web
    - host: kurrier-dav.vanclanjr.io
      paths:
        - path: /
          pathType: Prefix
          service: dav
  tls:
    - secretName: kurrier-tls
      hosts:
        - kurrier.vanclanjr.io
    - secretName: kurrier-dav-tls
      hosts:
        - kurrier-dav.vanclanjr.io

podDisruptionBudget:
  enabled: true
