{{- if and .Values.dav.enabled .Values.dav.baikal.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kurrier.fullname" . }}-baikal
  labels:
    {{- include "kurrier.baikal.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "kurrier.baikal.serviceName" . }}
  replicas: {{ .Values.dav.baikal.replicaCount }}
  selector:
    matchLabels:
      {{- include "kurrier.baikal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.dav.baikal.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kurrier.baikal.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "kurrier.imagePullSecrets" (dict "Values" .Values "componentPullSecrets" nil) | nindent 6 }}
      serviceAccountName: {{ include "kurrier.serviceAccountName" . }}
      initContainers:
        - name: init-config
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              # Create config directory structure if needed
              mkdir -p /var/www/baikal/config
              mkdir -p /var/www/baikal/Specific/db

              # Create baikal.yaml config if it doesn't exist
              if [ ! -f /var/www/baikal/config/baikal.yaml ]; then
                cat > /var/www/baikal/config/baikal.yaml << 'EOF'
              system:
                configured_version: 0.10.1
                base_uri: /
                invite_from: noreply@example.com
                auth_realm: BaikalDAV
                card_enabled: true
                cal_enabled: true
                dav_auth_type: Basic
              database:
                sqlite_file: Specific/db/db.sqlite
                encryption_key: ''
                backend: sqlite
              logger:
                log_path: ''
              EOF
              fi
          volumeMounts:
            - name: config
              mountPath: /var/www/baikal/config
            - name: data
              mountPath: /var/www/baikal/Specific
      containers:
        - name: baikal
          image: "{{ .Values.dav.baikal.image.repository }}:{{ .Values.dav.baikal.image.tag }}"
          imagePullPolicy: {{ .Values.dav.baikal.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /var/www/baikal/config
            - name: data
              mountPath: /var/www/baikal/Specific
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.dav.baikal.resources | nindent 12 }}
      volumes:
        - name: config
          emptyDir: {}
      {{- with .Values.dav.baikal.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dav.baikal.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dav.baikal.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.dav.baikal.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          {{- toYaml .Values.dav.baikal.persistence.accessModes | nindent 10 }}
        {{- if or .Values.global.storageClass .Values.dav.baikal.persistence.storageClass }}
        storageClassName: {{ .Values.dav.baikal.persistence.storageClass | default .Values.global.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.dav.baikal.persistence.size }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kurrier.baikal.serviceName" . }}
  labels:
    {{- include "kurrier.baikal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dav.baikal.service.type }}
  ports:
    - port: {{ .Values.dav.baikal.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kurrier.baikal.selectorLabels" . | nindent 4 }}
{{- end }}
