{{- if and .Values.dav.enabled .Values.dav.baikal.enabled }}
# NOTE: Using Deployment instead of StatefulSet because Baikal shares the
# kurrier-dav-data PVC with the worker. The worker creates DAV users/principals
# in the shared SQLite database at /dav-data/db/db.sqlite.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kurrier.fullname" . }}-baikal
  labels:
    {{- include "kurrier.baikal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dav.baikal.replicaCount }}
  {{- with .Values.dav.baikal.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kurrier.baikal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.dav.baikal.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kurrier.baikal.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "kurrier.imagePullSecrets" (dict "Values" .Values "componentPullSecrets" nil) | nindent 6 }}
      serviceAccountName: {{ include "kurrier.serviceAccountName" . }}
      initContainers:
        # Initialize Baikal config and database using the Baikal image (has sqlite3)
        - name: init-baikal
          image: "{{ .Values.dav.baikal.image.repository }}:{{ .Values.dav.baikal.image.tag }}"
          command:
            - sh
            - -c
            - |
              set -e

              echo "=== Baikal Initialization ==="

              # Create directory structure
              mkdir -p /var/www/baikal/config
              # Symlink Specific/db to the shared DAV data volume
              rm -rf /var/www/baikal/Specific/db
              mkdir -p /var/www/baikal/Specific
              ln -sf /dav-data/db /var/www/baikal/Specific/db

              # Write Baikal configuration
              # IMPORTANT: admin_passwordhash and timezone are REQUIRED
              # IMPORTANT: sqlite_file points to shared DAV database created by worker
              echo "Writing baikal.yaml configuration..."
              cat > /var/www/baikal/config/baikal.yaml << 'YAML'
              system:
                configured_version: 0.10.1
                base_uri: /
                invite_from: {{ .Values.dav.baikal.config.inviteFrom | default "noreply@example.com" }}
                auth_realm: {{ .Values.dav.baikal.config.authRealm | default "BaikalDAV" }}
                card_enabled: true
                cal_enabled: true
                dav_auth_type: Basic
                admin_passwordhash: '{{ required "dav.baikal.config.adminPasswordHash is required - generate with: php -r \"echo password_hash('yourpassword', PASSWORD_DEFAULT);\"" .Values.dav.baikal.config.adminPasswordHash }}'
                timezone: {{ .Values.dav.baikal.config.timezone | default "UTC" }}
              database:
                backend: sqlite
                sqlite_file: /dav-data/db/db.sqlite
                encryption_key: ''
              logger:
                log_path: ''
              YAML

              # Initialize SQLite database if it doesn't exist
              # NOTE: This database is shared with the worker via kurrier-dav-data PVC
              DB_FILE="/dav-data/db/db.sqlite"
              if [ ! -f "$DB_FILE" ]; then
                echo "Initializing Baikal SQLite database..."

                # Create database with schema
                sqlite3 "$DB_FILE" << 'SQL'
              -- Baikal/SabreDAV SQLite Schema
              CREATE TABLE addressbookchanges (
                  id integer primary key asc NOT NULL,
                  uri TEXT NOT NULL,
                  synctoken integer NOT NULL,
                  addressbookid integer NOT NULL,
                  operation integer NOT NULL
              );
              CREATE TABLE addressbooks (
                  id integer primary key asc NOT NULL,
                  principaluri TEXT NOT NULL,
                  displayname TEXT,
                  uri TEXT NOT NULL,
                  description TEXT,
                  synctoken integer DEFAULT 1 NOT NULL,
                  UNIQUE(principaluri, uri)
              );
              CREATE TABLE calendarchanges (
                  id integer primary key asc NOT NULL,
                  uri TEXT NOT NULL,
                  synctoken integer NOT NULL,
                  calendarid integer NOT NULL,
                  operation integer NOT NULL
              );
              CREATE TABLE calendarinstances (
                  id integer primary key asc NOT NULL,
                  calendarid integer,
                  principaluri text,
                  access integer,
                  displayname text,
                  uri text NOT NULL,
                  description text,
                  calendarorder integer,
                  calendarcolor text,
                  timezone text,
                  transparent bool,
                  share_href text,
                  share_displayname text,
                  share_invitestatus integer DEFAULT '2',
                  UNIQUE (principaluri, uri),
                  UNIQUE (calendarid, principaluri),
                  UNIQUE (calendarid, share_href)
              );
              CREATE TABLE calendarobjects (
                  id integer primary key asc NOT NULL,
                  calendardata blob NOT NULL,
                  uri TEXT NOT NULL,
                  calendarid integer NOT NULL,
                  lastmodified integer,
                  etag TEXT NOT NULL,
                  size integer NOT NULL,
                  componenttype TEXT NOT NULL,
                  firstoccurence integer,
                  lastoccurence integer,
                  uid TEXT,
                  UNIQUE(calendarid, uri)
              );
              CREATE TABLE calendars (
                  id integer primary key asc NOT NULL,
                  synctoken integer DEFAULT 1 NOT NULL,
                  components text NOT NULL
              );
              CREATE TABLE calendarsubscriptions (
                  id integer primary key asc NOT NULL,
                  uri TEXT NOT NULL,
                  principaluri TEXT NOT NULL,
                  source TEXT,
                  displayname TEXT,
                  refreshrate TEXT,
                  calendarorder integer,
                  calendarcolor TEXT,
                  striptodos integer,
                  stripalarms integer,
                  stripattachments integer,
                  lastmodified integer,
                  UNIQUE(principaluri, uri)
              );
              CREATE TABLE cards (
                  id integer primary key asc NOT NULL,
                  addressbookid integer NOT NULL,
                  carddata blob NOT NULL,
                  uri TEXT NOT NULL,
                  lastmodified integer,
                  etag TEXT NOT NULL,
                  size integer NOT NULL,
                  UNIQUE(addressbookid, uri)
              );
              CREATE TABLE groupmembers (
                  id integer primary key asc NOT NULL,
                  principal_id integer NOT NULL,
                  member_id integer NOT NULL,
                  UNIQUE (principal_id, member_id)
              );
              CREATE TABLE locks (
                  id integer primary key asc NOT NULL,
                  owner TEXT,
                  timeout integer,
                  created integer,
                  token TEXT NOT NULL,
                  scope integer,
                  depth integer,
                  uri TEXT NOT NULL
              );
              CREATE TABLE principals (
                  id INTEGER PRIMARY KEY ASC NOT NULL,
                  uri TEXT NOT NULL,
                  email TEXT,
                  displayname TEXT,
                  UNIQUE(uri)
              );
              CREATE TABLE propertystorage (
                  id integer primary key asc NOT NULL,
                  path TEXT NOT NULL,
                  name TEXT NOT NULL,
                  valuetype integer,
                  value TEXT,
                  UNIQUE (path, name)
              );
              CREATE TABLE schedulingobjects (
                  id integer primary key asc NOT NULL,
                  principaluri TEXT NOT NULL,
                  calendardata blob,
                  uri TEXT NOT NULL,
                  lastmodified integer,
                  etag TEXT NOT NULL,
                  size integer NOT NULL
              );
              CREATE TABLE users (
                  id integer primary key asc NOT NULL,
                  username TEXT NOT NULL,
                  digesta1 TEXT NOT NULL,
                  UNIQUE(username)
              );
              CREATE INDEX addressbookchanges_addressbookid_synctoken ON addressbookchanges (addressbookid, synctoken);
              CREATE INDEX calendarchanges_calendarid_synctoken ON calendarchanges (calendarid, synctoken);
              CREATE INDEX calendarobjects_calendarid_uid ON calendarobjects (calendarid, uid);
              SQL

                echo "SQLite database initialized successfully"
              else
                echo "SQLite database already exists, verifying schema..."
                TABLES=$(sqlite3 "$DB_FILE" ".tables" 2>/dev/null || echo "")
                if [ -z "$TABLES" ]; then
                  echo "ERROR: Database exists but has no tables!"
                  rm -f "$DB_FILE"
                  echo "Removed corrupt database, please restart the pod"
                  exit 1
                fi
                echo "Database verified: $TABLES"
              fi

              # Ensure correct permissions (nginx user in baikal container is uid 101)
              # The shared dav-data volume is also used by worker (uid 1000)
              chown -R 101:101 /var/www/baikal/config /var/www/baikal/Specific
              chmod 777 /dav-data/db
              chmod 666 "$DB_FILE" 2>/dev/null || true

              echo "=== Baikal Initialization Complete ==="
          volumeMounts:
            - name: config
              mountPath: /var/www/baikal/config
            - name: dav-data
              mountPath: /dav-data
            - name: specific
              mountPath: /var/www/baikal/Specific
      containers:
        - name: baikal
          image: "{{ .Values.dav.baikal.image.repository }}:{{ .Values.dav.baikal.image.tag }}"
          imagePullPolicy: {{ .Values.dav.baikal.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /var/www/baikal/config
            - name: dav-data
              mountPath: /dav-data
            - name: specific
              mountPath: /var/www/baikal/Specific
          # Use TCP probe since /dav.php/ returns 401 without auth (which fails HTTP probe)
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.dav.baikal.resources | nindent 12 }}
      volumes:
        - name: config
          emptyDir: {}
        - name: specific
          emptyDir: {}
        - name: dav-data
          {{- if .Values.dav.worker.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "kurrier.fullname" . }}-dav-data
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.dav.baikal.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dav.baikal.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dav.baikal.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kurrier.baikal.serviceName" . }}
  labels:
    {{- include "kurrier.baikal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dav.baikal.service.type }}
  ports:
    - port: {{ .Values.dav.baikal.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kurrier.baikal.selectorLabels" . | nindent 4 }}
{{- end }}
