{{- if and .Values.dav.enabled .Values.dav.worker.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kurrier.fullname" . }}-dav-data
  labels:
    {{- include "kurrier.labels" . | nindent 4 }}
    app.kubernetes.io/component: dav
spec:
  accessModes:
    {{- toYaml .Values.dav.worker.persistence.accessModes | nindent 4 }}
  {{- if or .Values.global.storageClass .Values.dav.worker.persistence.storageClass }}
  storageClassName: {{ .Values.dav.worker.persistence.storageClass | default .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.dav.worker.persistence.size }}
{{- end }}
