{{- if and .Values.dav.enabled .Values.dav.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kurrier.fullname" . }}-dav-specific
  labels:
    {{- include "kurrier.componentLabels" (dict "root" . "component" "dav") | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.dav.persistence.accessModes | nindent 4 }}
  {{- include "kurrier.storageClass" (dict "root" . "storageClass" .Values.dav.persistence.storageClass) | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.dav.persistence.size }}
{{- end }}
