{{- if .Values.gateway.enabled -}}
{{- $fullName := include "kurrier.fullname" . -}}
{{- $webSvcPort := .Values.web.service.port -}}
{{- $kongSvcPort := .Values.supabase.kong.service.httpPort -}}
{{- $studioSvcPort := .Values.supabase.studio.service.port -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "kurrier.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.gateway.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostnames:
    {{- range .Values.gateway.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    {{- if .Values.web.enabled }}
    # Web dashboard - catch-all for main UI
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $fullName }}-web
          port: {{ $webSvcPort }}
    {{- end }}
    {{- if and .Values.supabase.enabled .Values.supabase.kong.enabled }}
    # Kong API Gateway - Supabase API endpoints
    - matches:
        - path:
            type: PathPrefix
            value: /rest/
      backendRefs:
        - name: {{ $fullName }}-kong
          port: {{ $kongSvcPort }}
    - matches:
        - path:
            type: PathPrefix
            value: /auth/
      backendRefs:
        - name: {{ $fullName }}-kong
          port: {{ $kongSvcPort }}
    - matches:
        - path:
            type: PathPrefix
            value: /storage/
      backendRefs:
        - name: {{ $fullName }}-kong
          port: {{ $kongSvcPort }}
    - matches:
        - path:
            type: PathPrefix
            value: /realtime/
      backendRefs:
        - name: {{ $fullName }}-kong
          port: {{ $kongSvcPort }}
    {{- end }}
    {{- if and .Values.supabase.enabled .Values.supabase.studio.enabled .Values.gateway.studioPath }}
    # Supabase Studio dashboard
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.gateway.studioPath }}
      backendRefs:
        - name: {{ $fullName }}-studio
          port: {{ $studioSvcPort }}
    {{- end }}
{{- end }}
