{{- if .Values.podDisruptionBudget.enabled }}
{{- range $component := list "web" "worker" }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kurrier.fullname" $ }}-{{ $component }}
  labels:
    {{- include "kurrier.componentLabels" (dict "root" $ "component" $component) | nindent 4 }}
spec:
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "kurrier.componentSelectorLabels" (dict "root" $ "component" $component) | nindent 6 }}
{{- end }}
{{- end }}
