{{- if not .Values.kurrier.jwt.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kurrier.jwt.secretName" . }}
  labels:
    {{- include "kurrier.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.kurrier.jwt.secret | quote }}
  anon-key: {{ .Values.kurrier.jwt.anonKey | quote }}
  service-role-key: {{ .Values.kurrier.jwt.serviceRoleKey | quote }}
{{- end }}
---
{{- if not .Values.kurrier.vault.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kurrier.vault.secretName" . }}
  labels:
    {{- include "kurrier.labels" . | nindent 4 }}
type: Opaque
stringData:
  vault-encryption-key: {{ .Values.kurrier.vault.encryptionKey | quote }}
{{- end }}
---
{{- if not .Values.kurrier.rls.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kurrier.rls.secretName" . }}
  labels:
    {{- include "kurrier.labels" . | nindent 4 }}
type: Opaque
stringData:
  rls-client-password: {{ .Values.kurrier.rls.clientPassword | quote }}
{{- end }}
---
{{- if and .Values.typesense.enabled (not .Values.typesense.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kurrier.typesense.secretName" . }}
  labels:
    {{- include "kurrier.typesense.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.typesense.apiKey | quote }}
{{- end }}
---
{{- if and (not .Values.externalPostgresql.enabled) (not .Values.externalPostgresql.existingSecret) .Values.externalPostgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-external-postgresql" (include "kurrier.fullname" .) }}
  labels:
    {{- include "kurrier.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.externalPostgresql.password | quote }}
{{- end }}
---
{{- if and .Values.externalRedis.enabled (not .Values.externalRedis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-external-redis" (include "kurrier.fullname" .) }}
  labels:
    {{- include "kurrier.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.externalRedis.password | quote }}
{{- end }}
---
{{- if and .Values.supabase.enabled .Values.supabase.studio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kurrier.fullname" . }}-studio
  labels:
    {{- include "kurrier.studio.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.supabase.studio.username | quote }}
  password: {{ .Values.supabase.studio.password | quote }}
{{- end }}
