{{- if .Values.webdav.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kurrier.fullname" . }}-webdav
  labels:
    {{- include "kurrier.webdav.labels" . | nindent 4 }}
data:
  config.yml: |
    address: 0.0.0.0
    port: 6065
    auth: false
    tls: false
    prefix: /
    debug: false

    directory: /data
    permissions: CRUD

    users: []
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kurrier.fullname" . }}-webdav
  labels:
    {{- include "kurrier.webdav.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "kurrier.webdav.serviceName" . }}
  replicas: {{ .Values.webdav.replicaCount }}
  selector:
    matchLabels:
      {{- include "kurrier.webdav.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values.webdav | toYaml | sha256sum }}
      {{- with .Values.webdav.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kurrier.webdav.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "kurrier.imagePullSecrets" (dict "Values" .Values "componentPullSecrets" nil) | nindent 6 }}
      serviceAccountName: {{ include "kurrier.serviceAccountName" . }}
      containers:
        - name: webdav
          image: "{{ .Values.webdav.image.repository }}:{{ .Values.webdav.image.tag }}"
          imagePullPolicy: {{ .Values.webdav.image.pullPolicy }}
          args:
            - --config
            - /config/config.yml
          ports:
            - name: http
              containerPort: 6065
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.webdav.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "kurrier.fullname" . }}-webdav
      {{- with .Values.webdav.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webdav.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webdav.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.webdav.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          {{- toYaml .Values.webdav.persistence.accessModes | nindent 10 }}
        {{- if or .Values.global.storageClass .Values.webdav.persistence.storageClass }}
        storageClassName: {{ .Values.webdav.persistence.storageClass | default .Values.global.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.webdav.persistence.size }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kurrier.webdav.serviceName" . }}
  labels:
    {{- include "kurrier.webdav.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webdav.service.type }}
  ports:
    - port: {{ .Values.webdav.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kurrier.webdav.selectorLabels" . | nindent 4 }}
{{- end }}
