{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kurrier.worker.serviceName" . }}
  labels:
    {{- include "kurrier.componentLabels" (dict "root" . "component" "worker") | nindent 4 }}
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - name: http
      port: {{ .Values.worker.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "kurrier.componentSelectorLabels" (dict "root" . "component" "worker") | nindent 4 }}
{{- end }}
