{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kurrier.worker.serviceName" . }}
  labels:
    {{- include "kurrier.worker.labels" . | nindent 4 }}
  {{- with .Values.worker.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kurrier.worker.selectorLabels" . | nindent 4 }}
{{- end }}
